version: '3.9'
services:
  mongo-express:
    build:
      context: ./     
      dockerfile: .docker/Dockerfile-mongo-express     
    image: mongo-express-srv:v1.0
    container_name: 'mongo-express-srv'
    restart: always
    depends_on:
      - mongo   
    mem_limit: 2048M
    mem_reservation: 1024M
    cpus: 2        
    ports:
      - "0.0.0.0:3000:8081"        
    env_file:
      - ./src/env/mongo-express-dev.env
    volumes:
      - type: bind
        source: ./src/wait-for/wait-for.sh
        target: /wait-for.sh
    entrypoint:
      - /bin/sh
      - /wait-for.sh
      - mongo:27017
      - --
      - tini
      - --
      - /docker-entrypoint.sh
    networks:
      - backend
   
  mongo:
    build:
      context: ./
      dockerfile: .docker/Dockerfile-mongodb
    image: mongo-srv:v1.0
    container_name: 'mongodb-srv'
    restart: always   
    mem_limit: 2048M
    mem_reservation: 1024M
    cpus: 2    
    ports:
      - "0.0.0.0:27100:27017"
    volumes:
      - type: bind
        source: ./.docker/conf/mongo_configdb
        target: /data/configd       
      - type: bind
        source: ./src/data
        target: /data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
