FROM mongo-express:latest

MAINTAINER Dhony Priniardi abu muhammad <dhony.priniardi@bintangpelajar.co.id>
   LABEL Name mongo-express
   LABEL Version latest
   LABEL Type database
   LABEL Vendor mongo


#RUN apk update && \
#    apk add --no-cache \
#          vim curl lynx iproute2 net-tools \
#          unzip tzdata

#ENV TZ=Asia/Jakarta
